import {
  POKEMON_LIST_URL,
  POKEMON_DETAIL_URL,
  POKEMON_EVOLUTION_CHAIN_URL,
  POKEMON_GENERATION_URL,
  POKEMON_SPECIE_URL,
  POKEMON_TYPE_URL,
} from "./url";

const urls = Object.freeze({
  POKEMON_LIST_URL,
  POKEMON_DETAIL_URL,
  POKEMON_EVOLUTION_CHAIN_URL,
  POKEMON_GENERATION_URL,
  POKEMON_SPECIE_URL,
  POKEMON_TYPE_URL,
});

export { urls };
