version: '3'

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=pokedex.pcabana.net
      - LETSENCRYPT_HOST=pokedex.pcabana.net
      - LETSENCRYPT_EMAIL=juanpx99@gmail.com
      - NODE_ENV=production
